<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitfc7978fb9a54e10c87d4070e9c7fd2ba
{
    public static $prefixLengthsPsr4 = array (
        'T' => 
        array (
            'Twilio\\' => 7,
        ),
        'P' => 
        array (
            'PHPMailer\\PHPMailer\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Twilio\\' => 
        array (
            0 => __DIR__ . '/..' . '/twilio/sdk/src/Twilio',
        ),
        'PHPMailer\\PHPMailer\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpmailer/phpmailer/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitfc7978fb9a54e10c87d4070e9c7fd2ba::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitfc7978fb9a54e10c87d4070e9c7fd2ba::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitfc7978fb9a54e10c87d4070e9c7fd2ba::$classMap;

        }, null, ClassLoader::class);
    }
}
